; Auto-generated. Do not edit!


(cl:in-package upperbodycore_msgs-msg)


;//! \htmlinclude avoidthatactionFeedback.msg.html

(cl:defclass <avoidthatactionFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:string
    :initform ""))
)

(cl:defclass avoidthatactionFeedback (<avoidthatactionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <avoidthatactionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'avoidthatactionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upperbodycore_msgs-msg:<avoidthatactionFeedback> is deprecated: use upperbodycore_msgs-msg:avoidthatactionFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <avoidthatactionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:feedback-val is deprecated.  Use upperbodycore_msgs-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <avoidthatactionFeedback>) ostream)
  "Serializes a message object of type '<avoidthatactionFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <avoidthatactionFeedback>) istream)
  "Deserializes a message object of type '<avoidthatactionFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<avoidthatactionFeedback>)))
  "Returns string type for a message object of type '<avoidthatactionFeedback>"
  "upperbodycore_msgs/avoidthatactionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'avoidthatactionFeedback)))
  "Returns string type for a message object of type 'avoidthatactionFeedback"
  "upperbodycore_msgs/avoidthatactionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<avoidthatactionFeedback>)))
  "Returns md5sum for a message object of type '<avoidthatactionFeedback>"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'avoidthatactionFeedback)))
  "Returns md5sum for a message object of type 'avoidthatactionFeedback"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<avoidthatactionFeedback>)))
  "Returns full string definition for message of type '<avoidthatactionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'avoidthatactionFeedback)))
  "Returns full string definition for message of type 'avoidthatactionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <avoidthatactionFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <avoidthatactionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'avoidthatactionFeedback
    (cl:cons ':feedback (feedback msg))
))
