; Auto-generated. Do not edit!


(cl:in-package upperbodycore_msgs-msg)


;//! \htmlinclude avoidThatGoal.msg.html

(cl:defclass <avoidThatGoal> (roslisp-msg-protocol:ros-message)
  ((input
    :reader input
    :initarg :input
    :type cl:integer
    :initform 0))
)

(cl:defclass avoidThatGoal (<avoidThatGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <avoidThatGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'avoidThatGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upperbodycore_msgs-msg:<avoidThatGoal> is deprecated: use upperbodycore_msgs-msg:avoidThatGoal instead.")))

(cl:ensure-generic-function 'input-val :lambda-list '(m))
(cl:defmethod input-val ((m <avoidThatGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:input-val is deprecated.  Use upperbodycore_msgs-msg:input instead.")
  (input m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <avoidThatGoal>) ostream)
  "Serializes a message object of type '<avoidThatGoal>"
  (cl:let* ((signed (cl:slot-value msg 'input)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <avoidThatGoal>) istream)
  "Deserializes a message object of type '<avoidThatGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'input) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<avoidThatGoal>)))
  "Returns string type for a message object of type '<avoidThatGoal>"
  "upperbodycore_msgs/avoidThatGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'avoidThatGoal)))
  "Returns string type for a message object of type 'avoidThatGoal"
  "upperbodycore_msgs/avoidThatGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<avoidThatGoal>)))
  "Returns md5sum for a message object of type '<avoidThatGoal>"
  "350f8291236c5b6fb3b8cfcb1672a02e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'avoidThatGoal)))
  "Returns md5sum for a message object of type 'avoidThatGoal"
  "350f8291236c5b6fb3b8cfcb1672a02e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<avoidThatGoal>)))
  "Returns full string definition for message of type '<avoidThatGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%int32 input~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'avoidThatGoal)))
  "Returns full string definition for message of type 'avoidThatGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%int32 input~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <avoidThatGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <avoidThatGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'avoidThatGoal
    (cl:cons ':input (input msg))
))
