; Auto-generated. Do not edit!


(cl:in-package upperbodycore_msgs-msg)


;//! \htmlinclude grip_emergencyGoal.msg.html

(cl:defclass <grip_emergencyGoal> (roslisp-msg-protocol:ros-message)
  ((destination
    :reader destination
    :initarg :destination
    :type cl:string
    :initform "")
   (object
    :reader object
    :initarg :object
    :type cl:string
    :initform ""))
)

(cl:defclass grip_emergencyGoal (<grip_emergencyGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <grip_emergencyGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'grip_emergencyGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upperbodycore_msgs-msg:<grip_emergencyGoal> is deprecated: use upperbodycore_msgs-msg:grip_emergencyGoal instead.")))

(cl:ensure-generic-function 'destination-val :lambda-list '(m))
(cl:defmethod destination-val ((m <grip_emergencyGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:destination-val is deprecated.  Use upperbodycore_msgs-msg:destination instead.")
  (destination m))

(cl:ensure-generic-function 'object-val :lambda-list '(m))
(cl:defmethod object-val ((m <grip_emergencyGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:object-val is deprecated.  Use upperbodycore_msgs-msg:object instead.")
  (object m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <grip_emergencyGoal>) ostream)
  "Serializes a message object of type '<grip_emergencyGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'destination))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'destination))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'object))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'object))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <grip_emergencyGoal>) istream)
  "Deserializes a message object of type '<grip_emergencyGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'destination) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'destination) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'object) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<grip_emergencyGoal>)))
  "Returns string type for a message object of type '<grip_emergencyGoal>"
  "upperbodycore_msgs/grip_emergencyGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'grip_emergencyGoal)))
  "Returns string type for a message object of type 'grip_emergencyGoal"
  "upperbodycore_msgs/grip_emergencyGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<grip_emergencyGoal>)))
  "Returns md5sum for a message object of type '<grip_emergencyGoal>"
  "19ab24e4f331773932823594673b8d88")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'grip_emergencyGoal)))
  "Returns md5sum for a message object of type 'grip_emergencyGoal"
  "19ab24e4f331773932823594673b8d88")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<grip_emergencyGoal>)))
  "Returns full string definition for message of type '<grip_emergencyGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%string destination~%string object~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'grip_emergencyGoal)))
  "Returns full string definition for message of type 'grip_emergencyGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%string destination~%string object~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <grip_emergencyGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'destination))
     4 (cl:length (cl:slot-value msg 'object))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <grip_emergencyGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'grip_emergencyGoal
    (cl:cons ':destination (destination msg))
    (cl:cons ':object (object msg))
))
