; Auto-generated. Do not edit!


(cl:in-package upperbodycore_msgs-msg)


;//! \htmlinclude sepantaFeedback.msg.html

(cl:defclass <sepantaFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:integer
    :initform 0))
)

(cl:defclass sepantaFeedback (<sepantaFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <sepantaFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'sepantaFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upperbodycore_msgs-msg:<sepantaFeedback> is deprecated: use upperbodycore_msgs-msg:sepantaFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <sepantaFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:feedback-val is deprecated.  Use upperbodycore_msgs-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <sepantaFeedback>) ostream)
  "Serializes a message object of type '<sepantaFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <sepantaFeedback>) istream)
  "Deserializes a message object of type '<sepantaFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<sepantaFeedback>)))
  "Returns string type for a message object of type '<sepantaFeedback>"
  "upperbodycore_msgs/sepantaFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'sepantaFeedback)))
  "Returns string type for a message object of type 'sepantaFeedback"
  "upperbodycore_msgs/sepantaFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<sepantaFeedback>)))
  "Returns md5sum for a message object of type '<sepantaFeedback>"
  "49ceb5b32ea3af22073ede4a0328249e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'sepantaFeedback)))
  "Returns md5sum for a message object of type 'sepantaFeedback"
  "49ceb5b32ea3af22073ede4a0328249e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<sepantaFeedback>)))
  "Returns full string definition for message of type '<sepantaFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'sepantaFeedback)))
  "Returns full string definition for message of type 'sepantaFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <sepantaFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <sepantaFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'sepantaFeedback
    (cl:cons ':feedback (feedback msg))
))
