headYaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headYaw
    joint_speed: 0.5

    motor:
        id: 125
        init: 512
        min: 324
        max: 700

headPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: headPitch
    joint_speed: 0.5

    motor:
        id: 122
        init: 650
        min: 512
        max: 700

rightshoulderYawm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightshoulderYawm
    joint_speed: 0.5

    motor:
        id: 111
        init: 2350
        min: 1024
        max: 2350

rightshoulderPitchm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightshoulderPitchm
    joint_speed: 0.5

    motor:
        id: 113
        init: 3400
        min: 2800
        max: 3500

rightshoulderRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightshoulderRoll
    joint_speed: 0.5
    motor:
        id: 115
        init: 1024
        min: 500
        max: 2048

rightelbowPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightelbowPitch
    joint_speed: 0.5
    motor:
        id: 116
        init: 2430
        min: 1700
        max: 2700

rightelbowRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightelbowRoll
    joint_speed: 0.5
    motor:
        id: 117
        init: 512
        min: 0
        max: 1024

rightwristPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightwristPitch
    joint_speed: 0.5
    motor:
        id: 118
        init: 512
        min: 0
        max: 1024

rightwristRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightwristRoll
    joint_speed: 0.5
    motor:
        id: 119
        init: 210
        min: 210
        max: 512
        
rightgripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: rightgripper
    joint_speed: 1
    motor:
        id: 120
        init: 512
        min: 0
        max: 512
        
 
leftshoulderYawm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftshoulderYawm
    joint_speed: 0.5

    motor:
        id: 101
        init: 380
        min: 380
        max: 2300

leftshoulderPitchm_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftshoulderPitchm
    joint_speed: 0.5

    motor:
        id: 103
        init: 3072
        min: 2048
        max: 3100

leftshoulderRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftshoulderRoll
    joint_speed: 0.5
    motor:
        id: 105
        init: 2500
        min: 2048
        max: 3000

leftelbowPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftelbowPitch
    joint_speed: 0.5
    motor:
        id: 106
        init: 2600
        min: 2048
        max: 3000

leftelbowRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftelbowRoll
    joint_speed: 0.5
    motor:
        id: 107
        init: 512
        min: 0
        max: 1024

leftwristPitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftwristPitch
    joint_speed: 0.5
    motor:
        id: 108
        init: 512
        min: 0
        max: 1024

leftwristRoll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftwristRoll
    joint_speed: 0.5
    motor:
        id: 109
        init: 512
        min: 300
        max: 560
        
leftgripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: leftgripper
    joint_speed: 1
    motor:
        id: 110
        init: 512
        min: 0
        max: 512

