"""autogenerated by genpy from upperbodycore_msgs/irsensor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class irsensor(genpy.Message):
  _md5sum = "5bc545fa276d41dab37b84fc4b75e375"
  _type = "upperbodycore_msgs/irsensor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 d0
int16 d1
int16 d2
int16 d3
int16 d4
int16 d5
int16 d6
int16 d7

"""
  __slots__ = ['d0','d1','d2','d3','d4','d5','d6','d7']
  _slot_types = ['int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       d0,d1,d2,d3,d4,d5,d6,d7

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(irsensor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.d0 is None:
        self.d0 = 0
      if self.d1 is None:
        self.d1 = 0
      if self.d2 is None:
        self.d2 = 0
      if self.d3 is None:
        self.d3 = 0
      if self.d4 is None:
        self.d4 = 0
      if self.d5 is None:
        self.d5 = 0
      if self.d6 is None:
        self.d6 = 0
      if self.d7 is None:
        self.d7 = 0
    else:
      self.d0 = 0
      self.d1 = 0
      self.d2 = 0
      self.d3 = 0
      self.d4 = 0
      self.d5 = 0
      self.d6 = 0
      self.d7 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8h.pack(_x.d0, _x.d1, _x.d2, _x.d3, _x.d4, _x.d5, _x.d6, _x.d7))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.d0, _x.d1, _x.d2, _x.d3, _x.d4, _x.d5, _x.d6, _x.d7,) = _struct_8h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8h.pack(_x.d0, _x.d1, _x.d2, _x.d3, _x.d4, _x.d5, _x.d6, _x.d7))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.d0, _x.d1, _x.d2, _x.d3, _x.d4, _x.d5, _x.d6, _x.d7,) = _struct_8h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8h = struct.Struct("<8h")
