/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg/user.msg
 *
 */


#ifndef UPPERBODYCORE_MSGS_MESSAGE_USER_H
#define UPPERBODYCORE_MSGS_MESSAGE_USER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <upperbodycore_msgs/joint.h>
#include <upperbodycore_msgs/joint.h>
#include <upperbodycore_msgs/joint.h>
#include <upperbodycore_msgs/joint.h>
#include <upperbodycore_msgs/joint.h>
#include <upperbodycore_msgs/joint.h>

namespace upperbodycore_msgs
{
template <class ContainerAllocator>
struct user_
{
  typedef user_<ContainerAllocator> Type;

  user_()
    : Head()
    , Torso()
    , RightHand()
    , LeftHand()
    , LeftFoot()
    , RightFoot()
    , id(0)  {
    }
  user_(const ContainerAllocator& _alloc)
    : Head(_alloc)
    , Torso(_alloc)
    , RightHand(_alloc)
    , LeftHand(_alloc)
    , LeftFoot(_alloc)
    , RightFoot(_alloc)
    , id(0)  {
    }



   typedef  ::upperbodycore_msgs::joint_<ContainerAllocator>  _Head_type;
  _Head_type Head;

   typedef  ::upperbodycore_msgs::joint_<ContainerAllocator>  _Torso_type;
  _Torso_type Torso;

   typedef  ::upperbodycore_msgs::joint_<ContainerAllocator>  _RightHand_type;
  _RightHand_type RightHand;

   typedef  ::upperbodycore_msgs::joint_<ContainerAllocator>  _LeftHand_type;
  _LeftHand_type LeftHand;

   typedef  ::upperbodycore_msgs::joint_<ContainerAllocator>  _LeftFoot_type;
  _LeftFoot_type LeftFoot;

   typedef  ::upperbodycore_msgs::joint_<ContainerAllocator>  _RightFoot_type;
  _RightFoot_type RightFoot;

   typedef int32_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::upperbodycore_msgs::user_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upperbodycore_msgs::user_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct user_

typedef ::upperbodycore_msgs::user_<std::allocator<void> > user;

typedef boost::shared_ptr< ::upperbodycore_msgs::user > userPtr;
typedef boost::shared_ptr< ::upperbodycore_msgs::user const> userConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upperbodycore_msgs::user_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upperbodycore_msgs::user_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upperbodycore_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'upperbodycore_msgs': ['/home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg', '/home/shaghayegh/catkin_ws/qtcreator-build/devel/share/upperbodycore_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::user_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::user_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::user_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::user_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::user_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::user_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upperbodycore_msgs::user_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3118245be98de8d397dad1fbd4d66719";
  }

  static const char* value(const ::upperbodycore_msgs::user_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3118245be98de8d3ULL;
  static const uint64_t static_value2 = 0x97dad1fbd4d66719ULL;
};

template<class ContainerAllocator>
struct DataType< ::upperbodycore_msgs::user_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upperbodycore_msgs/user";
  }

  static const char* value(const ::upperbodycore_msgs::user_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upperbodycore_msgs::user_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joint Head\n\
joint Torso\n\
joint RightHand\n\
joint LeftHand\n\
joint LeftFoot\n\
joint RightFoot\n\
int32 id\n\
\n\
================================================================================\n\
MSG: upperbodycore_msgs/joint\n\
int32 x\n\
int32 y\n\
int32 z\n\
int32 img_x\n\
int32 img_y\n\
int32 mode\n\
";
  }

  static const char* value(const ::upperbodycore_msgs::user_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upperbodycore_msgs::user_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Head);
      stream.next(m.Torso);
      stream.next(m.RightHand);
      stream.next(m.LeftHand);
      stream.next(m.LeftFoot);
      stream.next(m.RightFoot);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct user_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upperbodycore_msgs::user_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upperbodycore_msgs::user_<ContainerAllocator>& v)
  {
    s << indent << "Head: ";
    s << std::endl;
    Printer< ::upperbodycore_msgs::joint_<ContainerAllocator> >::stream(s, indent + "  ", v.Head);
    s << indent << "Torso: ";
    s << std::endl;
    Printer< ::upperbodycore_msgs::joint_<ContainerAllocator> >::stream(s, indent + "  ", v.Torso);
    s << indent << "RightHand: ";
    s << std::endl;
    Printer< ::upperbodycore_msgs::joint_<ContainerAllocator> >::stream(s, indent + "  ", v.RightHand);
    s << indent << "LeftHand: ";
    s << std::endl;
    Printer< ::upperbodycore_msgs::joint_<ContainerAllocator> >::stream(s, indent + "  ", v.LeftHand);
    s << indent << "LeftFoot: ";
    s << std::endl;
    Printer< ::upperbodycore_msgs::joint_<ContainerAllocator> >::stream(s, indent + "  ", v.LeftFoot);
    s << indent << "RightFoot: ";
    s << std::endl;
    Printer< ::upperbodycore_msgs::joint_<ContainerAllocator> >::stream(s, indent + "  ", v.RightFoot);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPERBODYCORE_MSGS_MESSAGE_USER_H
