set(_CATKIN_CURRENT_PACKAGE "upperbodycore_msgs")
set(upperbodycore_msgs_MAINTAINER "thome <thome@todo.todo>")
set(upperbodycore_msgs_DEPRECATED "")
set(upperbodycore_msgs_VERSION "0.0.0")
set(upperbodycore_msgs_BUILD_DEPENDS "std_msgs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(upperbodycore_msgs_RUN_DEPENDS "std_msgs" "geometry_msgs" "nav_msgs" "message_runtime" "actionlib_msgs")
set(upperbodycore_msgs_BUILDTOOL_DEPENDS "catkin")