/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg/upperbodymotors.msg
 *
 */


#ifndef UPPERBODYCORE_MSGS_MESSAGE_UPPERBODYMOTORS_H
#define UPPERBODYCORE_MSGS_MESSAGE_UPPERBODYMOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upperbodycore_msgs
{
template <class ContainerAllocator>
struct upperbodymotors_
{
  typedef upperbodymotors_<ContainerAllocator> Type;

  upperbodymotors_()
    : shoulder_yawm_position(0)
    , shoulder_pitchm_position(0)
    , shoulder_roll_position(0)
    , elbow_pitch_position(0)
    , elbow_roll_position(0)
    , wrist_pitch_position(0)
    , wrist_roll_position(0)
    , gripper_position(0)
    , shoulder_yawm_speed(0)
    , shoulder_pitchm_speed(0)
    , shoulder_roll_speed(0)
    , elbow_pitch_speed(0)
    , elbow_roll_speed(0)
    , wrist_pitch_speed(0)
    , wrist_roll_speed(0)
    , gripper_speed(0)
    , head_yaw_position(0)
    , head_yaw_speed(0)
    , head_pitch_position(0)
    , head_pitch_speed(0)  {
    }
  upperbodymotors_(const ContainerAllocator& _alloc)
    : shoulder_yawm_position(0)
    , shoulder_pitchm_position(0)
    , shoulder_roll_position(0)
    , elbow_pitch_position(0)
    , elbow_roll_position(0)
    , wrist_pitch_position(0)
    , wrist_roll_position(0)
    , gripper_position(0)
    , shoulder_yawm_speed(0)
    , shoulder_pitchm_speed(0)
    , shoulder_roll_speed(0)
    , elbow_pitch_speed(0)
    , elbow_roll_speed(0)
    , wrist_pitch_speed(0)
    , wrist_roll_speed(0)
    , gripper_speed(0)
    , head_yaw_position(0)
    , head_yaw_speed(0)
    , head_pitch_position(0)
    , head_pitch_speed(0)  {
    }



   typedef int32_t _shoulder_yawm_position_type;
  _shoulder_yawm_position_type shoulder_yawm_position;

   typedef int32_t _shoulder_pitchm_position_type;
  _shoulder_pitchm_position_type shoulder_pitchm_position;

   typedef int32_t _shoulder_roll_position_type;
  _shoulder_roll_position_type shoulder_roll_position;

   typedef int32_t _elbow_pitch_position_type;
  _elbow_pitch_position_type elbow_pitch_position;

   typedef int32_t _elbow_roll_position_type;
  _elbow_roll_position_type elbow_roll_position;

   typedef int32_t _wrist_pitch_position_type;
  _wrist_pitch_position_type wrist_pitch_position;

   typedef int32_t _wrist_roll_position_type;
  _wrist_roll_position_type wrist_roll_position;

   typedef int32_t _gripper_position_type;
  _gripper_position_type gripper_position;

   typedef int32_t _shoulder_yawm_speed_type;
  _shoulder_yawm_speed_type shoulder_yawm_speed;

   typedef int32_t _shoulder_pitchm_speed_type;
  _shoulder_pitchm_speed_type shoulder_pitchm_speed;

   typedef int32_t _shoulder_roll_speed_type;
  _shoulder_roll_speed_type shoulder_roll_speed;

   typedef int32_t _elbow_pitch_speed_type;
  _elbow_pitch_speed_type elbow_pitch_speed;

   typedef int32_t _elbow_roll_speed_type;
  _elbow_roll_speed_type elbow_roll_speed;

   typedef int32_t _wrist_pitch_speed_type;
  _wrist_pitch_speed_type wrist_pitch_speed;

   typedef int32_t _wrist_roll_speed_type;
  _wrist_roll_speed_type wrist_roll_speed;

   typedef int32_t _gripper_speed_type;
  _gripper_speed_type gripper_speed;

   typedef int32_t _head_yaw_position_type;
  _head_yaw_position_type head_yaw_position;

   typedef int32_t _head_yaw_speed_type;
  _head_yaw_speed_type head_yaw_speed;

   typedef int32_t _head_pitch_position_type;
  _head_pitch_position_type head_pitch_position;

   typedef int32_t _head_pitch_speed_type;
  _head_pitch_speed_type head_pitch_speed;




  typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct upperbodymotors_

typedef ::upperbodycore_msgs::upperbodymotors_<std::allocator<void> > upperbodymotors;

typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotors > upperbodymotorsPtr;
typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotors const> upperbodymotorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upperbodycore_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'upperbodycore_msgs': ['/home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg', '/home/shaghayegh/catkin_ws/devel/share/upperbodycore_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fffca84754f6d1b715c73f8c10cb67a1";
  }

  static const char* value(const ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfffca84754f6d1b7ULL;
  static const uint64_t static_value2 = 0x15c73f8c10cb67a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upperbodycore_msgs/upperbodymotors";
  }

  static const char* value(const ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 shoulder_yawm_position\n\
int32 shoulder_pitchm_position\n\
int32 shoulder_roll_position\n\
int32 elbow_pitch_position\n\
int32 elbow_roll_position\n\
int32 wrist_pitch_position\n\
int32 wrist_roll_position\n\
int32 gripper_position\n\
int32 shoulder_yawm_speed\n\
int32 shoulder_pitchm_speed\n\
int32 shoulder_roll_speed\n\
int32 elbow_pitch_speed\n\
int32 elbow_roll_speed\n\
int32 wrist_pitch_speed\n\
int32 wrist_roll_speed\n\
int32 gripper_speed\n\
int32 head_yaw_position\n\
int32 head_yaw_speed\n\
int32 head_pitch_position\n\
int32 head_pitch_speed\n\
";
  }

  static const char* value(const ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shoulder_yawm_position);
      stream.next(m.shoulder_pitchm_position);
      stream.next(m.shoulder_roll_position);
      stream.next(m.elbow_pitch_position);
      stream.next(m.elbow_roll_position);
      stream.next(m.wrist_pitch_position);
      stream.next(m.wrist_roll_position);
      stream.next(m.gripper_position);
      stream.next(m.shoulder_yawm_speed);
      stream.next(m.shoulder_pitchm_speed);
      stream.next(m.shoulder_roll_speed);
      stream.next(m.elbow_pitch_speed);
      stream.next(m.elbow_roll_speed);
      stream.next(m.wrist_pitch_speed);
      stream.next(m.wrist_roll_speed);
      stream.next(m.gripper_speed);
      stream.next(m.head_yaw_position);
      stream.next(m.head_yaw_speed);
      stream.next(m.head_pitch_position);
      stream.next(m.head_pitch_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct upperbodymotors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upperbodycore_msgs::upperbodymotors_<ContainerAllocator>& v)
  {
    s << indent << "shoulder_yawm_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shoulder_yawm_position);
    s << indent << "shoulder_pitchm_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shoulder_pitchm_position);
    s << indent << "shoulder_roll_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shoulder_roll_position);
    s << indent << "elbow_pitch_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.elbow_pitch_position);
    s << indent << "elbow_roll_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.elbow_roll_position);
    s << indent << "wrist_pitch_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wrist_pitch_position);
    s << indent << "wrist_roll_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wrist_roll_position);
    s << indent << "gripper_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gripper_position);
    s << indent << "shoulder_yawm_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shoulder_yawm_speed);
    s << indent << "shoulder_pitchm_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shoulder_pitchm_speed);
    s << indent << "shoulder_roll_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.shoulder_roll_speed);
    s << indent << "elbow_pitch_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.elbow_pitch_speed);
    s << indent << "elbow_roll_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.elbow_roll_speed);
    s << indent << "wrist_pitch_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wrist_pitch_speed);
    s << indent << "wrist_roll_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wrist_roll_speed);
    s << indent << "gripper_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gripper_speed);
    s << indent << "head_yaw_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.head_yaw_position);
    s << indent << "head_yaw_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.head_yaw_speed);
    s << indent << "head_pitch_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.head_pitch_position);
    s << indent << "head_pitch_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.head_pitch_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPERBODYCORE_MSGS_MESSAGE_UPPERBODYMOTORS_H
