/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg/upperbodymotorsfeedback.msg
 *
 */


#ifndef UPPERBODYCORE_MSGS_MESSAGE_UPPERBODYMOTORSFEEDBACK_H
#define UPPERBODYCORE_MSGS_MESSAGE_UPPERBODYMOTORSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <upperbodycore_msgs/motorfeedback.h>

namespace upperbodycore_msgs
{
template <class ContainerAllocator>
struct upperbodymotorsfeedback_
{
  typedef upperbodymotorsfeedback_<ContainerAllocator> Type;

  upperbodymotorsfeedback_()
    : motorfeedbacks()  {
    }
  upperbodymotorsfeedback_(const ContainerAllocator& _alloc)
    : motorfeedbacks(_alloc)  {
    }



   typedef std::vector< ::upperbodycore_msgs::motorfeedback_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::upperbodycore_msgs::motorfeedback_<ContainerAllocator> >::other >  _motorfeedbacks_type;
  _motorfeedbacks_type motorfeedbacks;




  typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct upperbodymotorsfeedback_

typedef ::upperbodycore_msgs::upperbodymotorsfeedback_<std::allocator<void> > upperbodymotorsfeedback;

typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotorsfeedback > upperbodymotorsfeedbackPtr;
typedef boost::shared_ptr< ::upperbodycore_msgs::upperbodymotorsfeedback const> upperbodymotorsfeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upperbodycore_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'upperbodycore_msgs': ['/home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg', '/home/shaghayegh/catkin_ws/devel/share/upperbodycore_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73917b09a0a2f6fb93332ecb105c3eb5";
  }

  static const char* value(const ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73917b09a0a2f6fbULL;
  static const uint64_t static_value2 = 0x93332ecb105c3eb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upperbodycore_msgs/upperbodymotorsfeedback";
  }

  static const char* value(const ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motorfeedback[] motorfeedbacks\n\
\n\
================================================================================\n\
MSG: upperbodycore_msgs/motorfeedback\n\
int32 speed\n\
int32 position\n\
float64 load\n\
int32 voltage\n\
int32 temp\n\
int32 id\n\
string name\n\
string status\n\
int32 min\n\
int32 max\n\
int32 init\n\
";
  }

  static const char* value(const ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorfeedbacks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct upperbodymotorsfeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upperbodycore_msgs::upperbodymotorsfeedback_<ContainerAllocator>& v)
  {
    s << indent << "motorfeedbacks[]" << std::endl;
    for (size_t i = 0; i < v.motorfeedbacks.size(); ++i)
    {
      s << indent << "  motorfeedbacks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::upperbodycore_msgs::motorfeedback_<ContainerAllocator> >::stream(s, indent + "    ", v.motorfeedbacks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPERBODYCORE_MSGS_MESSAGE_UPPERBODYMOTORSFEEDBACK_H
