/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg/users.msg
 *
 */


#ifndef UPPERBODYCORE_MSGS_MESSAGE_USERS_H
#define UPPERBODYCORE_MSGS_MESSAGE_USERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <upperbodycore_msgs/user.h>

namespace upperbodycore_msgs
{
template <class ContainerAllocator>
struct users_
{
  typedef users_<ContainerAllocator> Type;

  users_()
    : count(0)
    , users()
    , z(0)
    , x(0)
    , tracked(0)  {
    }
  users_(const ContainerAllocator& _alloc)
    : count(0)
    , users(_alloc)
    , z(0)
    , x(0)
    , tracked(0)  {
    }



   typedef int32_t _count_type;
  _count_type count;

   typedef std::vector< ::upperbodycore_msgs::user_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::upperbodycore_msgs::user_<ContainerAllocator> >::other >  _users_type;
  _users_type users;

   typedef int32_t _z_type;
  _z_type z;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _tracked_type;
  _tracked_type tracked;




  typedef boost::shared_ptr< ::upperbodycore_msgs::users_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upperbodycore_msgs::users_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct users_

typedef ::upperbodycore_msgs::users_<std::allocator<void> > users;

typedef boost::shared_ptr< ::upperbodycore_msgs::users > usersPtr;
typedef boost::shared_ptr< ::upperbodycore_msgs::users const> usersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upperbodycore_msgs::users_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upperbodycore_msgs::users_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upperbodycore_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'upperbodycore_msgs': ['/home/shaghayegh/catkin_ws/src/upperbodycore_msgs/msg', '/home/shaghayegh/catkin_ws/devel/share/upperbodycore_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::users_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upperbodycore_msgs::users_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::users_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upperbodycore_msgs::users_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::users_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upperbodycore_msgs::users_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upperbodycore_msgs::users_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a00c3d88998fc0bf609372f1044891e";
  }

  static const char* value(const ::upperbodycore_msgs::users_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a00c3d88998fc0bULL;
  static const uint64_t static_value2 = 0xf609372f1044891eULL;
};

template<class ContainerAllocator>
struct DataType< ::upperbodycore_msgs::users_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upperbodycore_msgs/users";
  }

  static const char* value(const ::upperbodycore_msgs::users_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upperbodycore_msgs::users_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 count\n\
user[] users\n\
int32 z\n\
int32 x\n\
int32 tracked\n\
\n\
\n\
================================================================================\n\
MSG: upperbodycore_msgs/user\n\
joint Head\n\
joint Torso\n\
joint RightHand\n\
joint LeftHand\n\
joint LeftFoot\n\
joint RightFoot\n\
int32 id\n\
\n\
================================================================================\n\
MSG: upperbodycore_msgs/joint\n\
int32 x\n\
int32 y\n\
int32 z\n\
int32 img_x\n\
int32 img_y\n\
int32 mode\n\
";
  }

  static const char* value(const ::upperbodycore_msgs::users_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upperbodycore_msgs::users_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
      stream.next(m.users);
      stream.next(m.z);
      stream.next(m.x);
      stream.next(m.tracked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct users_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upperbodycore_msgs::users_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upperbodycore_msgs::users_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "users[]" << std::endl;
    for (size_t i = 0; i < v.users.size(); ++i)
    {
      s << indent << "  users[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::upperbodycore_msgs::user_<ContainerAllocator> >::stream(s, indent + "    ", v.users[i]);
    }
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "tracked: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tracked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPPERBODYCORE_MSGS_MESSAGE_USERS_H
