set(_CATKIN_CURRENT_PACKAGE "pgitic_play_sound")
set(pgitic_play_sound_MAINTAINER "pgitic_record_motors <PGITIC_vision@todo.todo>")
set(pgitic_play_sound_DEPRECATED "")
set(pgitic_play_sound_VERSION "0.0.0")
set(pgitic_play_sound_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "cv_bridge" "image_transport" "upperbodycore_msgs" "actionlib" "actionlib_msgs")
set(pgitic_play_sound_RUN_DEPENDS "message_runtime" "actionlib" "actionlib_msgs" "image_transport" "cv_bridge" "sensor_msgs" "roscpp" "rospy" "std_msgs" "upperbodycore_msgs")
set(pgitic_play_sound_BUILDTOOL_DEPENDS "catkin")