; Auto-generated. Do not edit!


(cl:in-package upperbodycore_msgs-msg)


;//! \htmlinclude grip_emergencyResult.msg.html

(cl:defclass <grip_emergencyResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:string
    :initform ""))
)

(cl:defclass grip_emergencyResult (<grip_emergencyResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <grip_emergencyResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'grip_emergencyResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upperbodycore_msgs-msg:<grip_emergencyResult> is deprecated: use upperbodycore_msgs-msg:grip_emergencyResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <grip_emergencyResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:result-val is deprecated.  Use upperbodycore_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <grip_emergencyResult>) ostream)
  "Serializes a message object of type '<grip_emergencyResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <grip_emergencyResult>) istream)
  "Deserializes a message object of type '<grip_emergencyResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'result) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<grip_emergencyResult>)))
  "Returns string type for a message object of type '<grip_emergencyResult>"
  "upperbodycore_msgs/grip_emergencyResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'grip_emergencyResult)))
  "Returns string type for a message object of type 'grip_emergencyResult"
  "upperbodycore_msgs/grip_emergencyResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<grip_emergencyResult>)))
  "Returns md5sum for a message object of type '<grip_emergencyResult>"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'grip_emergencyResult)))
  "Returns md5sum for a message object of type 'grip_emergencyResult"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<grip_emergencyResult>)))
  "Returns full string definition for message of type '<grip_emergencyResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the result~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'grip_emergencyResult)))
  "Returns full string definition for message of type 'grip_emergencyResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the result~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <grip_emergencyResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <grip_emergencyResult>))
  "Converts a ROS message object to a list"
  (cl:list 'grip_emergencyResult
    (cl:cons ':result (result msg))
))
