; Auto-generated. Do not edit!


(cl:in-package upperbodycore_msgs-msg)


;//! \htmlinclude pickAndPlaceGoal.msg.html

(cl:defclass <pickAndPlaceGoal> (roslisp-msg-protocol:ros-message)
  ((input
    :reader input
    :initarg :input
    :type cl:string
    :initform ""))
)

(cl:defclass pickAndPlaceGoal (<pickAndPlaceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pickAndPlaceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pickAndPlaceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name upperbodycore_msgs-msg:<pickAndPlaceGoal> is deprecated: use upperbodycore_msgs-msg:pickAndPlaceGoal instead.")))

(cl:ensure-generic-function 'input-val :lambda-list '(m))
(cl:defmethod input-val ((m <pickAndPlaceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader upperbodycore_msgs-msg:input-val is deprecated.  Use upperbodycore_msgs-msg:input instead.")
  (input m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pickAndPlaceGoal>) ostream)
  "Serializes a message object of type '<pickAndPlaceGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'input))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'input))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pickAndPlaceGoal>) istream)
  "Deserializes a message object of type '<pickAndPlaceGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'input) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'input) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pickAndPlaceGoal>)))
  "Returns string type for a message object of type '<pickAndPlaceGoal>"
  "upperbodycore_msgs/pickAndPlaceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pickAndPlaceGoal)))
  "Returns string type for a message object of type 'pickAndPlaceGoal"
  "upperbodycore_msgs/pickAndPlaceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pickAndPlaceGoal>)))
  "Returns md5sum for a message object of type '<pickAndPlaceGoal>"
  "39e92f1778057359c64c7b8a7d7b19de")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pickAndPlaceGoal)))
  "Returns md5sum for a message object of type 'pickAndPlaceGoal"
  "39e92f1778057359c64c7b8a7d7b19de")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pickAndPlaceGoal>)))
  "Returns full string definition for message of type '<pickAndPlaceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%string input~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pickAndPlaceGoal)))
  "Returns full string definition for message of type 'pickAndPlaceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# define the goal~%string input~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pickAndPlaceGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'input))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pickAndPlaceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'pickAndPlaceGoal
    (cl:cons ':input (input msg))
))
