set(_CATKIN_CURRENT_PACKAGE "pgitic_wave")
set(pgitic_wave_MAINTAINER "PGITIC_vision_skeleton <PGITIC_vision@todo.todo>")
set(pgitic_wave_DEPRECATED "")
set(pgitic_wave_VERSION "0.0.0")
set(pgitic_wave_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "cv_bridge" "image_transport" "upperbodycore_msgs" "actionlib" "actionlib_msgs")
set(pgitic_wave_RUN_DEPENDS "message_runtime" "actionlib" "actionlib_msgs" "image_transport" "cv_bridge" "sensor_msgs" "roscpp" "rospy" "std_msgs" "upperbodycore_msgs")
set(pgitic_wave_BUILDTOOL_DEPENDS "catkin")