set(_CATKIN_CURRENT_PACKAGE "upperbodycore")
set(upperbodycore_MAINTAINER "x <x@gmail.com>")
set(upperbodycore_DEPRECATED "")
set(upperbodycore_VERSION "0.0.1")
set(upperbodycore_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "tf" "std_msgs" "geometry_msgs" "nav_msgs" "actionlib" "actionlib_msgs" "dynamixel_msgs" "upperbodycore_msgs")
set(upperbodycore_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "nav_msgs" "tf" "message_runtime" "actionlib" "actionlib_msgs" "dynamixel_msgs" "upperbodycore_msgs")
set(upperbodycore_BUILDTOOL_DEPENDS "catkin")